# Generated by Django 3.2.5 on 2021-07-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0002_cursosusuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosusuarios',
            options={'verbose_name': 'CursoUsuario', 'verbose_name_plural': 'CursosUsuarios'},
        ),
    ]
