# Generated by Django 3.2.5 on 2021-07-21 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0003_alter_cursosusuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosusuarios',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursosusuarios',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
