# Generated by Django 3.2.5 on 2021-07-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0004_auto_20210721_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='Nada', max_length=40),
        ),
    ]
