# Generated by Django 3.2.5 on 2021-07-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0005_notificacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
