# Generated by Django 3.2.5 on 2021-08-01 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionCursos', '0006_alter_notificacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aceptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('CursosUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.cursosusuarios')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceptado',
                'verbose_name_plural': 'Aceptados',
            },
        ),
    ]
