# Generated by Django 3.2.5 on 2021-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0008_auto_20210801_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='pendientes',
            field=models.IntegerField(default=0),
        ),
    ]
