# Generated by Django 3.2.5 on 2021-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0010_p1t1i_p1t1v_p2t2i_p3t1i_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p1t1i',
            name='img1',
            field=models.ImageField(upload_to='img1_P1T1I'),
        ),
        migrations.AlterField(
            model_name='p2t2i',
            name='img1',
            field=models.ImageField(upload_to='img1_P2T2I'),
        ),
        migrations.AlterField(
            model_name='p2t2i',
            name='img2',
            field=models.ImageField(upload_to='img2_P2T2I'),
        ),
        migrations.AlterField(
            model_name='p3t1i',
            name='img1',
            field=models.ImageField(upload_to='img1_P3T1I'),
        ),
    ]
